language: node_js
node_js:
  - '4.5.0'

services:
  - mongodb

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script: mocha test

notifications:
 email: false
 slack: izc:QTO0Q2SGJDXaH2mXood1ui7M